apiVersion: apps/v1
kind: Deployment
metadata:
  name: flutter-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flutter-frontend
  template:
    metadata:
      labels:
        app: flutter-frontend
    spec:
      containers:
      - name: flutter-frontend
        image: myregistryname.azurecr.io/flutter-frontend:latest
        ports:
        - containerPort: 80
